apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma
  namespace: ragforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      enableServiceLinks: false
      containers:
        - name: chroma
          image: chromadb/chroma:0.5.0
          ports:
            - containerPort: 8000
          env:
            - name: IS_PERSISTENT
              value: "TRUE"
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma/chroma
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: chroma-pvc
